### PR TITLE
Ensure that workers don't re-use openings unless unavoidable

### PR DESCRIPTION
**Pull request by snowdrop4**
Problem:

- Each workload is seeded with `time.time()`, and this seed is used to randomise positions in the opening book.
- Even if the seeds for each workload are different, collisions  in the opening positions used can still happen due to RNG

Solution:

- Move the calculation of the number of games in total to play, and the number of games to play concurrently, out of the client and into server
- Make sure that each worker samples from different sets of opening positions:
    - Add an opening book starting position column to the test model
    - Dynamically compute the opening book starting position for each workload, and increment this column in the model in a thread-safe way after handing out a workload
    - Use the same opening book random seed for every workload, so that if each worker uses our specified starting position, the openings it uses won't be repeats of the openings any other worker uses
    - This all means that the only way opening positions will get re-used is if the number games exceeds the size of the opening book

Random minor things:
- add type annotations for the few functions that I touched
- Use `None` as the failure return type for `get_workload()` instead of an empty dictionary, to make the logic clearer

### CODE REVIEW

**Comment by AndyGrant** [comment]
Okay; trying to piece together this PR with the SPSA PR ( https://github.com/AndyGrant/OpenBench/pull/169 )

I yoinked a chunk of your PR when doing the SPSA PR, which also required me to compute the # of games the worker is going to play, ON the server side.

Summary of your PR is:
1. Add book_position as a field to the Test Model. It can start at 0 (?)
2. Every time we assign a workload, increment book_position by the # of pairs we'll play
3. Send that (pre-incremented) value to the worker. And send the test-id explicitly. We'll add two fields to the workload JSON.

This PR never actually sets the book seed stuff [here](https://github.com/AndyGrant/OpenBench/pull/168/files#diff-66ad0b411a9d7fbbe2c196c6456cc7ca3c178177886293fdcdda468f05f4a10bR425-R430 )

```python
    def book_settings(config):

        # Can handle EPD and PGN Books, which must be specified
        book_name   = config.workload['test']['book']['name']
        book_suffix = book_name.split('.')[-1]
        return '-openings file=Books/%s format=%s order=random plies=16' % (book_name, book_suffix)
```

---

**There is still a critical question that I don't think is addressed by this comment:**

```python
        # We don't need to worry about possibly specifying a start position
        # greater than the number of openings in the book, as CuteChess
        # intelligently handles this case for us, by computing the real start
        # position by taking the specified start position modulo the book size.```

I don't know the exact words to describe this but here is my thinking...

We provide a seed S, and a start position P. Cutechess will be smart, and say `P = P % size_of_book`. This means we are safe to increment P ad infinitum, and Cutechess will handle this. However there is a tricky issue here. I still want Cutechess to play random openings, not sequentially through the book at a given starting point. Assuming this is possible.

So when we send P to Cutechess, we really want Cutechess to skip the first P-random openings it would generate, and then start from there. I suppose the logic of `P = P % size_of_book` still works in this case. But I don't know exactly how cutechess handles the concept of "start position"?

**Comment by snowdrop4** [comment]
> This PR never actually sets the book seed stuff here

Wups. I added the field to the JSON for the RNG seed but forgot to use it :sweat_smile:

**Comment by snowdrop4** [comment]
> So when we send P to Cutechess, we really want Cutechess to skip the first P-random openings it would generate, and then start from there. I suppose the logic of `P = P % size_of_book` still works in this case. But I don't know exactly how cutechess handles the concept of "start position"?

Cute chess stores a shuffled version of the book in a buffer, then takes `P = P % size_of_book`, and then uses that value as the start position inside the shuffled buffer.

**Comment by snowdrop4** [comment]
First worker payload:

```python
{
    "result": {"id": 10},
    "test": {
        "id": 12,
        "syzygy_wdl": "DISABLED",
        "syzygy_adj": "OPTIONAL",
        "win_adj": "movecount=5 score=300",
        "draw_adj": "movenumber=32 movecount=6 score=8",
        "workload_size": 32,
        "book": {
            "name": "UHO_4060_v2.epd",
            "sha": "36f2ec751ab78def6be1307430cbe2cd2ba65ade8d2aaae8f10e3df7d0ea83e1",
            "source": "https://raw.githubusercontent.com/AndyGrant/OpenBench/master/Books/UHO_4060_v2.epd.zip",
        },
        "book_rng_seed": 12,
        "book_start_pos": 1,
        "number_of_games_to_play": 256,
        "concurrent_games_per_socket": 8,
        "dev": {
            "id": 5,
            "name": "master",
            "source": "https://api.github.com/repos/ChessCom/TorchDev/actions/runs/6224902154/artifacts",
            "sha": "7a5d1270ac00a2a2d2f4350f65ad56adecc92655",
            "bench": 6248635,
            "engine": "Torch",
            "options": "Threads=1 Hash=16 Minimal=true",
            "network": "D3C75AA5",
            "time_control": "10.0+0.10",
            "nps": 560000,
            "build": {
                "cpuflags": ["AVX2", "FMA", "POPCNT"],
                "systems": ["Linux"],
                "private": True,
            },
            "private": True,
        },
        "base": {
            "id": 5,
            "name": "master",
            "source": "https://api.github.com/repos/ChessCom/TorchDev/actions/runs/6224902154/artifacts",
            "sha": "7a5d1270ac00a2a2d2f4350f65ad56adecc92655",
            "bench": 6248635,
            "engine": "Torch",
            "options": "Threads=1 Hash=16 Minimal=true",
            "network": "D3C75AA5",
            "time_control": "10.0+0.10",
            "nps": 560000,
            "build": {
                "cpuflags": ["AVX2", "FMA", "POPCNT"],
                "systems": ["Linux"],
                "private": True,
            },
            "private": True,
        },
    },
}
```

results in running the command:

```bash
./cutechess-ob -repeat -recover -variant standard -concurrency 8 -games 256 -resign movecount=5 score=300 -draw movenumber=32 movecount=6 score=8  -engine dir=Engines/ cmd=./Torch-7A5D1270 proto=uci tc=2.80+0.03 timemargin=250 option.Threads=1 option.Hash=16 option.Minimal=true option.EvalFile=../Networks/D3C75AA5 name=Torch-7A5D1270-D3C75AA5-dev -engine dir=Engines/ cmd=./Torch-7A5D1270 proto=uci tc=2.80+0.03 timemargin=250 option.Threads=1 option.Hash=16 option.Minimal=true option.EvalFile=../Networks/D3C75AA5 name=Torch-7A5D1270-D3C75AA5-base -openings file=Books/UHO_4060_v2.epd format=epd order=random plies=16 start=1 -srand 12  -pgnout PGNs/12.10.1695124062.0.pgn
```

---

Second worker payload:

```python
{
    "result": {"id": 10},
    "test": {
        "id": 12,
        "syzygy_wdl": "DISABLED",
        "syzygy_adj": "OPTIONAL",
        "win_adj": "movecount=5 score=300",
        "draw_adj": "movenumber=32 movecount=6 score=8",
        "workload_size": 32,
        "book": {
            "name": "UHO_4060_v2.epd",
            "sha": "36f2ec751ab78def6be1307430cbe2cd2ba65ade8d2aaae8f10e3df7d0ea83e1",
            "source": "https://raw.githubusercontent.com/AndyGrant/OpenBench/master/Books/UHO_4060_v2.epd.zip",
        },
        "book_rng_seed": 12,
        "book_start_pos": 257,
        "number_of_games_to_play": 256,
        "concurrent_games_per_socket": 8,
        "dev": {
            "id": 5,
            "name": "master",
            "source": "https://api.github.com/repos/ChessCom/TorchDev/actions/runs/6224902154/artifacts",
            "sha": "7a5d1270ac00a2a2d2f4350f65ad56adecc92655",
            "bench": 6248635,
            "engine": "Torch",
            "options": "Threads=1 Hash=16 Minimal=true",
            "network": "D3C75AA5",
            "time_control": "10.0+0.10",
            "nps": 560000,
            "build": {
                "cpuflags": ["AVX2", "FMA", "POPCNT"],
                "systems": ["Linux"],
                "private": True,
            },
            "private": True,
        },
        "base": {
            "id": 5,
            "name": "master",
            "source": "https://api.github.com/repos/ChessCom/TorchDev/actions/runs/6224902154/artifacts",
            "sha": "7a5d1270ac00a2a2d2f4350f65ad56adecc92655",
            "bench": 6248635,
            "engine": "Torch",
            "options": "Threads=1 Hash=16 Minimal=true",
            "network": "D3C75AA5",
            "time_control": "10.0+0.10",
            "nps": 560000,
            "build": {
                "cpuflags": ["AVX2", "FMA", "POPCNT"],
                "systems": ["Linux"],
                "private": True,
            },
            "private": True,
        },
    },
}
```

results in running the command:

```bash
./cutechess-ob -repeat -recover -variant standard -concurrency 8 -games 256 -resign movecount=5 score=300 -draw movenumber=32 movecount=6 score=8  -engine dir=Engines/ cmd=./Torch-7A5D1270 proto=uci tc=3.37+0.03 timemargin=250 option.Threads=1 option.Hash=16 option.Minimal=true option.EvalFile=../Networks/D3C75AA5 name=Torch-7A5D1270-D3C75AA5-dev -engine dir=Engines/ cmd=./Torch-7A5D1270 proto=uci tc=3.37+0.03 timemargin=250 option.Threads=1 option.Hash=16 option.Minimal=true option.EvalFile=../Networks/D3C75AA5 name=Torch-7A5D1270-D3C75AA5-base -openings file=Books/UHO_4060_v2.epd format=epd order=random plies=16 start=257 -srand 12  -pgnout PGNs/12.10.1695124071.0.pgn
```

**Comment by AndyGrant** [comment]
Closed; so I can merge against master.

**Pull request closed without merging**
